# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 098ebf4358e8ca0ec846c61920866d8d02cc05dc27f00dafb9f49ba673a6245785cb4690214842addfef061616a0506665fd16c9464bcc6ff98dc2e4fcdedc89

test:
  secret_key_base: b619d75811383ad24ade74bb6d6d30d6d458e7278fa459f5253dabe7bc35fb304deed5edeb97489c37ebd4f6c54d1637919651b50a8e21de2016c300ab9b6e88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
